# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, Linux, Vulkan]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake Clang Debug
        run: cmake -G "Ninja" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-14 -DCMAKE_CXX_COMPILER=clang++-14

      - name: Build Clang Debug
        run: cmake --build ${{github.workspace}}/build -j

      - name: Run Tests
        run: ${{github.workspace}}/build/test/GameXTest
